plugins:
  etiquette_enabled:
    default: true
    client: true
  etiquette_flag_post_min_toxicity_confidence:
    default: 0.9
  etiquette_notify_posting_min_toxicity_confidence:
    default: 0.7
  etiquette_google_api_key:
    default: ''
  etiquette_check_private_message:
    default: false
